#Stage 1
FROM node:17-alpine as builder
WORKDIR /mnt
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
EXPOSE 9090
RUN npm run build

#Stage 2
FROM nginx:1.19.0
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /mnt/build .
ENTRYPOINT ["nginx", "-g", "daemon off;"]
